/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package esprit.pidev.accueil;



import esprit.pidev.shadow.AdminMenu;
import esprit.pidev.gui.chalgoumi_marwen.frame_choice;
import esprit.pidev.shadow.CommercantMenu;
import esprit.pidev.dao.ClientDAO;
import esprit.pidev.dao.CommercantDAO;
import esprit.pidev.dao.adminDAO;
import esprit.pidev.entities.Client;
import esprit.pidev.entities.Commercant;
import esprit.pidev.entities.administrateur;
import esprit.pidev.facebook.Main;
import esprit.pidev.shadow.ClientMenu;
import esprit.pidev.util.MyConnection;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Chala
 */
public class frame_aceuil extends javax.swing.JFrame {
public static int idlog;
    /**
     * Creates new form frame_aceuil
     */
    Statement ste;
    MyConnection cnx;

    public frame_aceuil() throws SQLException {
        
        
          try {
            // select Look and Feel Theme 1
            //UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
         // select Look and Feel Theme 2
           //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
                    
            // select Look and Feel Theme 3
           UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
          //Voici des liens utiles :
           //http://www.jtattoo.net/ 
            
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
        
        
        initComponents();
        // (sans Singleton)
        // cnx = ConnectionSQL.getInstance();//  (Singleton)récupération de l'instance de la classe ConnectionMySQL.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb_commercant = new javax.swing.JRadioButton();
        rb_client = new javax.swing.JRadioButton();
        rb_admin = new javax.swing.JRadioButton();
        fbbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Login :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(51, 271, 70, 17);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(185, 268, 122, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mot de passe :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 320, 110, 17);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(791, 158, 189, 0);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(185, 315, 122, 20);

        jLabel6.setForeground(new java.awt.Color(102, 51, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/pidev/image/bouton-inscrire.png"))); // NOI18N
        jLabel6.setText("s'engistrer ");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 434, 110, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/pidev/image/connecter_btn.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 360, 168, 42);

        buttonGroup1.add(rb_commercant);
        rb_commercant.setText("Commerçant");
        jPanel1.add(rb_commercant);
        rb_commercant.setBounds(364, 320, 120, 23);

        buttonGroup1.add(rb_client);
        rb_client.setText("Client");
        jPanel1.add(rb_client);
        rb_client.setBounds(364, 294, 120, 23);

        buttonGroup1.add(rb_admin);
        rb_admin.setSelected(true);
        rb_admin.setText("Administrateur");
        jPanel1.add(rb_admin);
        rb_admin.setBounds(364, 268, 120, 23);

        fbbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/pidev/image/fb.png"))); // NOI18N
        fbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(fbbutton);
        fbbutton.setBounds(540, 430, 179, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/pidev/image/deal (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public List affichercommercant() throws SQLException {
        List<Commercant> listcommercant = new ArrayList<Commercant>();

        String requete = "select * from commercant";
        try {
            Statement statement = MyConnection.getInstance()
                    .createStatement();
            ResultSet resultat = statement.executeQuery(requete);

            while (resultat.next()) {
                Commercant commercant2 = new Commercant();
                commercant2.setLogin(resultat.getString(1));
                commercant2.setPassword(resultat.getString(2));

                listcommercant.add(commercant2);
            }
            return listcommercant;
        } catch (SQLException ex) {
            //Logger.getLogger(PersonneDao.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erreur lors du chargement des depots " + ex.getMessage());
            return null;
        }
    }

   



    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        this.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_formWindowOpened

    private void fbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbbuttonActionPerformed
        // TODO add your handling code here:
        String[] args=null;
        Main mff = new Main();
        mff.main(args);
        this.dispose();
    }//GEN-LAST:event_fbbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (rb_admin.isSelected()) {
            adminDAO adao = new adminDAO();
            administrateur admin = adao.findAdminByLogin(jTextField1.getText());
            if (admin != null) {
                if (admin.getPassword().equals(jPasswordField2.getText())) {

                    idlog=admin.getId_admin();

                    AdminMenu f1 = new AdminMenu();
                    this.dispose();

                    f1.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Mot de passe incorrect", "Error", 1);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login incorrect ! ", "Error", 1);
            }
        }
        if (rb_client.isSelected()) {
            ClientDAO clt = new ClientDAO();
            Client client = clt.findclientByLogin(jTextField1.getText());
            if (client != null) {
                if (client.getPassword().equals(jPasswordField2.getText())) {
                    idlog=client.getId_client();
                    ClientMenu f1 = new ClientMenu();

                    this.dispose();
                    f1.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Mot de passe incorrect", "Error", 1);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login incorrect ! ", "Error", 1);
            }
        }

        if (rb_commercant.isSelected()) {
            CommercantDAO com = new CommercantDAO();
            Commercant commercant = com.findCommByLogin(jTextField1.getText());
            if (commercant != null) {
                if (commercant.getPassword().equals(jPasswordField2.getText())) {

                    idlog=commercant.getId_commercant();

                    CommercantMenu f1 = new CommercantMenu();
                    this.dispose();
                    f1.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Mot de passe incorrect", "Error", 1);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login incorrect ! ", "Error", 1);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        frame_choice f3 = new frame_choice();
        f3.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_aceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_aceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_aceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_aceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new frame_aceuil().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frame_aceuil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton fbbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rb_admin;
    private javax.swing.JRadioButton rb_client;
    private javax.swing.JRadioButton rb_commercant;
    // End of variables declaration//GEN-END:variables
}
